
package localhost._8080.namegenerator;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NameGeneratorService", targetNamespace = "http://localhost:8080/NameGenerator")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NameGeneratorService {


    /**
     * 
     * @param arg0
     * @return
     *     returns localhost._8080.namegenerator.Gender
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mapStringToGender", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.MapStringToGender")
    @ResponseWrapper(localName = "mapStringToGenderResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.MapStringToGenderResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/mapStringToGenderRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/mapStringToGenderResponse")
    public Gender mapStringToGender(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastNameSyllables", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GetLastNameSyllables")
    @ResponseWrapper(localName = "getLastNameSyllablesResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GetLastNameSyllablesResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/getLastNameSyllablesRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/getLastNameSyllablesResponse")
    public List<String> getLastNameSyllables();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaleFirstNameSyllables", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GetMaleFirstNameSyllables")
    @ResponseWrapper(localName = "getMaleFirstNameSyllablesResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GetMaleFirstNameSyllablesResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/getMaleFirstNameSyllablesRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/getMaleFirstNameSyllablesResponse")
    public List<String> getMaleFirstNameSyllables();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFemaleFirstNameSyllables", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GetFemaleFirstNameSyllables")
    @ResponseWrapper(localName = "getFemaleFirstNameSyllablesResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GetFemaleFirstNameSyllablesResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/getFemaleFirstNameSyllablesRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/getFemaleFirstNameSyllablesResponse")
    public List<String> getFemaleFirstNameSyllables();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateFirstName", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GenerateFirstName")
    @ResponseWrapper(localName = "generateFirstNameResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GenerateFirstNameResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/generateFirstNameRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/generateFirstNameResponse")
    public String generateFirstName(
        @WebParam(name = "arg0", targetNamespace = "")
        Gender arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateName", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GenerateName")
    @ResponseWrapper(localName = "generateNameResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GenerateNameResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/generateNameRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/generateNameResponse")
    public String generateName(
        @WebParam(name = "arg0", targetNamespace = "")
        Gender arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateLastName", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GenerateLastName")
    @ResponseWrapper(localName = "generateLastNameResponse", targetNamespace = "http://localhost:8080/NameGenerator", className = "localhost._8080.namegenerator.GenerateLastNameResponse")
    @Action(input = "http://localhost:8080/NameGenerator/NameGeneratorService/generateLastNameRequest", output = "http://localhost:8080/NameGenerator/NameGeneratorService/generateLastNameResponse")
    public String generateLastName(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
